<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__Publication__CLASSMETADATA__' => 0,
'App__Entity__Communication__CLASSMETADATA__' => 1,

], [

0 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Publication',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\PublicationRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'titre' => $o[2],
                    'description' => $o[3],
                    'dateCreation' => $o[4],
                    'categorie' => $o[5],
                    'nombreVues' => $o[6],
                    'nombreLikes' => $o[7],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'titre' => 'titre',
                    'description' => 'description',
                    'date_creation' => 'dateCreation',
                    'categorie' => 'categorie',
                    'nombre_vues' => 'nombreVues',
                    'nombre_likes' => 'nombreLikes',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'titre' => 'titre',
                    'description' => 'description',
                    'dateCreation' => 'date_creation',
                    'categorie' => 'categorie',
                    'nombreVues' => 'nombre_vues',
                    'nombreLikes' => 'nombre_likes',
                ],
            ],
            'table' => [
                [
                    'name' => 'publication',
                ],
            ],
            'lifecycleCallbacks' => [
                [
                    'prePersist' => [
                        'setCreatedAtValue',
                    ],
                ],
            ],
            'associationMappings' => [
                [
                    'communications' => $o[8],
                ],
            ],
            'idGenerator' => [
                $o[9],
            ],
            'name' => [
                'App\\Entity\\Publication',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'text',
                'datetime',
                'string',
                'integer',
                'integer',
            ],
            'fieldName' => [
                1 => 'id',
                'titre',
                'description',
                'dateCreation',
                'categorie',
                'nombreVues',
                'nombreLikes',
            ],
            'columnName' => [
                1 => 'id',
                'titre',
                'description',
                'date_creation',
                'categorie',
                'nombre_vues',
                'nombre_likes',
            ],
            'length' => [
                2 => 255,
                5 => 100,
            ],
            'cascade' => [
                8 => [
                    'remove',
                ],
            ],
            'fetch' => [
                8 => 2,
            ],
            'orphanRemoval' => [
                8 => true,
            ],
            'sourceEntity' => [
                8 => 'App\\Entity\\Publication',
            ],
            'mappedBy' => [
                8 => 'publication',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                8 => 'communications',
            ],
            'targetEntity' => [
                8 => 'App\\Entity\\Communication',
            ],
        ],
    ],
    $o[0],
    []
); } },
1 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Communication',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\CommunicationRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'type' => $o[2],
                    'lien' => $o[3],
                    'dateHeure' => $o[4],
                    'duree' => $o[5],
                    'etat' => $o[6],
                    'descriptionDetaillee' => $o[7],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'type' => 'type',
                    'lien' => 'lien',
                    'date_heure' => 'dateHeure',
                    'duree' => 'duree',
                    'etat' => 'etat',
                    'description_detaillee' => 'descriptionDetaillee',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'type' => 'type',
                    'lien' => 'lien',
                    'dateHeure' => 'date_heure',
                    'duree' => 'duree',
                    'etat' => 'etat',
                    'descriptionDetaillee' => 'description_detaillee',
                ],
            ],
            'table' => [
                [
                    'name' => 'communication',
                ],
            ],
            'associationMappings' => [
                [
                    'publication' => $o[8],
                ],
            ],
            'idGenerator' => [
                $o[10],
            ],
            'name' => [
                'App\\Entity\\Communication',
                9 => 'publication_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'string',
                'datetime',
                'integer',
                'string',
                'text',
            ],
            'fieldName' => [
                1 => 'id',
                'type',
                'lien',
                'dateHeure',
                'duree',
                'etat',
                'descriptionDetaillee',
            ],
            'columnName' => [
                1 => 'id',
                'type',
                'lien',
                'date_heure',
                'duree',
                'etat',
                'description_detaillee',
            ],
            'length' => [
                2 => 50,
                500,
                6 => 50,
            ],
            'nullable' => [
                3 => true,
                5 => true,
                7 => true,
                9 => false,
            ],
            'fetch' => [
                8 => 2,
            ],
            'sourceEntity' => [
                8 => 'App\\Entity\\Communication',
            ],
            'inversedBy' => [
                8 => 'communications',
            ],
            'sourceToTargetKeyColumns' => [
                8 => [
                    'publication_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                8 => [
                    'id' => 'publication_id',
                ],
            ],
            'joinColumns' => [
                8 => [
                    $o[9],
                ],
            ],
            'joinColumnFieldNames' => [
                8 => [
                    'publication_id' => 'publication_id',
                ],
            ],
            'deferrable' => [
                9 => false,
            ],
            'unique' => [
                9 => false,
            ],
            'referencedColumnName' => [
                9 => 'id',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                8 => 'publication',
            ],
            'targetEntity' => [
                8 => 'App\\Entity\\Publication',
            ],
        ],
    ],
    $o[0],
    []
); } },

]];
