<?php

namespace ContainerLKXGGTj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Z0uo5zSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.z0uo5zS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'publicationRepo' => ['privates', 'App\\Repository\\PublicationRepository', 'getPublicationRepositoryService', true],
        ], [
            'em' => '?',
            'publicationRepo' => 'App\\Repository\\PublicationRepository',
        ]);

        if (isset($container->privates['.service_locator.z0uo5zS'])) {
            return $container->privates['.service_locator.z0uo5zS'];
        }

        return $container->privates['.service_locator.z0uo5zS'] = $instance;
    }
}
