<?php

namespace ContainerLKXGGTj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OiApXmRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oiApXmR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\BackPublicationController::delete' => ['privates', '.service_locator.xsWtpa9', 'get_ServiceLocator_XsWtpa9Service', true],
            'App\\Controller\\BackPublicationController::edit' => ['privates', '.service_locator.xsWtpa9', 'get_ServiceLocator_XsWtpa9Service', true],
            'App\\Controller\\BackPublicationController::exportPdf' => ['privates', '.service_locator.4knxYxY', 'get_ServiceLocator_4knxYxYService', true],
            'App\\Controller\\BackPublicationController::index' => ['privates', '.service_locator.tigx378', 'get_ServiceLocator_Tigx378Service', true],
            'App\\Controller\\BackPublicationController::new' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\BackPublicationController::show' => ['privates', '.service_locator.4knxYxY', 'get_ServiceLocator_4knxYxYService', true],
            'App\\Controller\\BackPublicationController::statistics' => ['privates', '.service_locator.4knxYxY', 'get_ServiceLocator_4knxYxYService', true],
            'App\\Controller\\CommunicationController::delete' => ['privates', '.service_locator.nSjV3Y2', 'get_ServiceLocator_NSjV3Y2Service', true],
            'App\\Controller\\CommunicationController::edit' => ['privates', '.service_locator.t2.BUGi', 'get_ServiceLocator_T2_BUGiService', true],
            'App\\Controller\\CommunicationController::exportPdf' => ['privates', '.service_locator._WS2NMT', 'get_ServiceLocator_WS2NMTService', true],
            'App\\Controller\\CommunicationController::index' => ['privates', '.service_locator.dGSEfNf', 'get_ServiceLocator_DGSEfNfService', true],
            'App\\Controller\\CommunicationController::new' => ['privates', '.service_locator.z0uo5zS', 'get_ServiceLocator_Z0uo5zSService', true],
            'App\\Controller\\CommunicationController::searchAdvanced' => ['privates', '.service_locator._WS2NMT', 'get_ServiceLocator_WS2NMTService', true],
            'App\\Controller\\CommunicationController::show' => ['privates', '.service_locator._WS2NMT', 'get_ServiceLocator_WS2NMTService', true],
            'App\\Controller\\CommunicationController::statistics' => ['privates', '.service_locator._WS2NMT', 'get_ServiceLocator_WS2NMTService', true],
            'App\\Controller\\FrontController::chat' => ['privates', '.service_locator.2VpSp_j', 'get_ServiceLocator_2VpSpJService', true],
            'App\\Controller\\FrontController::checkMessages' => ['privates', '.service_locator._WS2NMT', 'get_ServiceLocator_WS2NMTService', true],
            'App\\Controller\\FrontController::communicationIndex' => ['privates', '.service_locator.2VpSp_j', 'get_ServiceLocator_2VpSpJService', true],
            'App\\Controller\\FrontController::deleteCommunication' => ['privates', '.service_locator.AL9KkA6', 'get_ServiceLocator_AL9KkA6Service', true],
            'App\\Controller\\FrontController::editCommunication' => ['privates', '.service_locator.AL9KkA6', 'get_ServiceLocator_AL9KkA6Service', true],
            'App\\Controller\\FrontController::forum' => ['privates', '.service_locator.rqjGJ0U', 'get_ServiceLocator_RqjGJ0UService', true],
            'App\\Controller\\FrontController::joinCommunication' => ['privates', '.service_locator.DyTFj._', 'get_ServiceLocator_DyTFj_Service', true],
            'App\\Controller\\FrontController::newCommunication' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\FrontController::newPublication' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\FrontController::showCommunication' => ['privates', '.service_locator.DyTFj._', 'get_ServiceLocator_DyTFj_Service', true],
            'App\\Controller\\FrontController::showPublication' => ['privates', '.service_locator.PFvSZhV', 'get_ServiceLocator_PFvSZhVService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\BackPublicationController:delete' => ['privates', '.service_locator.xsWtpa9', 'get_ServiceLocator_XsWtpa9Service', true],
            'App\\Controller\\BackPublicationController:edit' => ['privates', '.service_locator.xsWtpa9', 'get_ServiceLocator_XsWtpa9Service', true],
            'App\\Controller\\BackPublicationController:exportPdf' => ['privates', '.service_locator.4knxYxY', 'get_ServiceLocator_4knxYxYService', true],
            'App\\Controller\\BackPublicationController:index' => ['privates', '.service_locator.tigx378', 'get_ServiceLocator_Tigx378Service', true],
            'App\\Controller\\BackPublicationController:new' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\BackPublicationController:show' => ['privates', '.service_locator.4knxYxY', 'get_ServiceLocator_4knxYxYService', true],
            'App\\Controller\\BackPublicationController:statistics' => ['privates', '.service_locator.4knxYxY', 'get_ServiceLocator_4knxYxYService', true],
            'App\\Controller\\CommunicationController:delete' => ['privates', '.service_locator.nSjV3Y2', 'get_ServiceLocator_NSjV3Y2Service', true],
            'App\\Controller\\CommunicationController:edit' => ['privates', '.service_locator.t2.BUGi', 'get_ServiceLocator_T2_BUGiService', true],
            'App\\Controller\\CommunicationController:exportPdf' => ['privates', '.service_locator._WS2NMT', 'get_ServiceLocator_WS2NMTService', true],
            'App\\Controller\\CommunicationController:index' => ['privates', '.service_locator.dGSEfNf', 'get_ServiceLocator_DGSEfNfService', true],
            'App\\Controller\\CommunicationController:new' => ['privates', '.service_locator.z0uo5zS', 'get_ServiceLocator_Z0uo5zSService', true],
            'App\\Controller\\CommunicationController:searchAdvanced' => ['privates', '.service_locator._WS2NMT', 'get_ServiceLocator_WS2NMTService', true],
            'App\\Controller\\CommunicationController:show' => ['privates', '.service_locator._WS2NMT', 'get_ServiceLocator_WS2NMTService', true],
            'App\\Controller\\CommunicationController:statistics' => ['privates', '.service_locator._WS2NMT', 'get_ServiceLocator_WS2NMTService', true],
            'App\\Controller\\FrontController:chat' => ['privates', '.service_locator.2VpSp_j', 'get_ServiceLocator_2VpSpJService', true],
            'App\\Controller\\FrontController:checkMessages' => ['privates', '.service_locator._WS2NMT', 'get_ServiceLocator_WS2NMTService', true],
            'App\\Controller\\FrontController:communicationIndex' => ['privates', '.service_locator.2VpSp_j', 'get_ServiceLocator_2VpSpJService', true],
            'App\\Controller\\FrontController:deleteCommunication' => ['privates', '.service_locator.AL9KkA6', 'get_ServiceLocator_AL9KkA6Service', true],
            'App\\Controller\\FrontController:editCommunication' => ['privates', '.service_locator.AL9KkA6', 'get_ServiceLocator_AL9KkA6Service', true],
            'App\\Controller\\FrontController:forum' => ['privates', '.service_locator.rqjGJ0U', 'get_ServiceLocator_RqjGJ0UService', true],
            'App\\Controller\\FrontController:joinCommunication' => ['privates', '.service_locator.DyTFj._', 'get_ServiceLocator_DyTFj_Service', true],
            'App\\Controller\\FrontController:newCommunication' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\FrontController:newPublication' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\FrontController:showCommunication' => ['privates', '.service_locator.DyTFj._', 'get_ServiceLocator_DyTFj_Service', true],
            'App\\Controller\\FrontController:showPublication' => ['privates', '.service_locator.PFvSZhV', 'get_ServiceLocator_PFvSZhVService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\BackPublicationController::delete' => '?',
            'App\\Controller\\BackPublicationController::edit' => '?',
            'App\\Controller\\BackPublicationController::exportPdf' => '?',
            'App\\Controller\\BackPublicationController::index' => '?',
            'App\\Controller\\BackPublicationController::new' => '?',
            'App\\Controller\\BackPublicationController::show' => '?',
            'App\\Controller\\BackPublicationController::statistics' => '?',
            'App\\Controller\\CommunicationController::delete' => '?',
            'App\\Controller\\CommunicationController::edit' => '?',
            'App\\Controller\\CommunicationController::exportPdf' => '?',
            'App\\Controller\\CommunicationController::index' => '?',
            'App\\Controller\\CommunicationController::new' => '?',
            'App\\Controller\\CommunicationController::searchAdvanced' => '?',
            'App\\Controller\\CommunicationController::show' => '?',
            'App\\Controller\\CommunicationController::statistics' => '?',
            'App\\Controller\\FrontController::chat' => '?',
            'App\\Controller\\FrontController::checkMessages' => '?',
            'App\\Controller\\FrontController::communicationIndex' => '?',
            'App\\Controller\\FrontController::deleteCommunication' => '?',
            'App\\Controller\\FrontController::editCommunication' => '?',
            'App\\Controller\\FrontController::forum' => '?',
            'App\\Controller\\FrontController::joinCommunication' => '?',
            'App\\Controller\\FrontController::newCommunication' => '?',
            'App\\Controller\\FrontController::newPublication' => '?',
            'App\\Controller\\FrontController::showCommunication' => '?',
            'App\\Controller\\FrontController::showPublication' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\BackPublicationController:delete' => '?',
            'App\\Controller\\BackPublicationController:edit' => '?',
            'App\\Controller\\BackPublicationController:exportPdf' => '?',
            'App\\Controller\\BackPublicationController:index' => '?',
            'App\\Controller\\BackPublicationController:new' => '?',
            'App\\Controller\\BackPublicationController:show' => '?',
            'App\\Controller\\BackPublicationController:statistics' => '?',
            'App\\Controller\\CommunicationController:delete' => '?',
            'App\\Controller\\CommunicationController:edit' => '?',
            'App\\Controller\\CommunicationController:exportPdf' => '?',
            'App\\Controller\\CommunicationController:index' => '?',
            'App\\Controller\\CommunicationController:new' => '?',
            'App\\Controller\\CommunicationController:searchAdvanced' => '?',
            'App\\Controller\\CommunicationController:show' => '?',
            'App\\Controller\\CommunicationController:statistics' => '?',
            'App\\Controller\\FrontController:chat' => '?',
            'App\\Controller\\FrontController:checkMessages' => '?',
            'App\\Controller\\FrontController:communicationIndex' => '?',
            'App\\Controller\\FrontController:deleteCommunication' => '?',
            'App\\Controller\\FrontController:editCommunication' => '?',
            'App\\Controller\\FrontController:forum' => '?',
            'App\\Controller\\FrontController:joinCommunication' => '?',
            'App\\Controller\\FrontController:newCommunication' => '?',
            'App\\Controller\\FrontController:newPublication' => '?',
            'App\\Controller\\FrontController:showCommunication' => '?',
            'App\\Controller\\FrontController:showPublication' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);

        if (isset($container->privates['.service_locator.oiApXmR'])) {
            return $container->privates['.service_locator.oiApXmR'];
        }

        return $container->privates['.service_locator.oiApXmR'] = $instance;
    }
}
