<?php

namespace ContainerLKXGGTj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DyTFj_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DyTFj._' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DyTFj._'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'communication' => ['privates', '.errored..service_locator.DyTFj._.App\\Entity\\Communication', NULL, 'Cannot autowire service ".service_locator.DyTFj._": it needs an instance of "App\\Entity\\Communication" but this type has been excluded in "config/services.yaml".'],
        ], [
            'communication' => 'App\\Entity\\Communication',
        ]);
    }
}
