<?php

namespace ContainerLKXGGTj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RqjGJ0UService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rqjGJ0U' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rqjGJ0U'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'communicationRepository' => ['privates', 'App\\Repository\\CommunicationRepository', 'getCommunicationRepositoryService', true],
            'publicationRepository' => ['privates', 'App\\Repository\\PublicationRepository', 'getPublicationRepositoryService', true],
        ], [
            'communicationRepository' => 'App\\Repository\\CommunicationRepository',
            'publicationRepository' => 'App\\Repository\\PublicationRepository',
        ]);
    }
}
