<?php

namespace ContainerGPhgrvV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BS3Flt3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BS3Flt3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BS3Flt3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'publication' => ['privates', '.errored..service_locator.BS3Flt3.App\\Entity\\Publication', NULL, 'Cannot autowire service ".service_locator.BS3Flt3": it needs an instance of "App\\Entity\\Publication" but this type has been excluded in "config/services.yaml".'],
        ], [
            'publication' => 'App\\Entity\\Publication',
        ]);
    }
}
