<?php

namespace ContainerGPhgrvV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2VpSpJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2VpSp_j' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2VpSp_j'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'communicationRepository' => ['privates', 'App\\Repository\\CommunicationRepository', 'getCommunicationRepositoryService', true],
        ], [
            'communicationRepository' => 'App\\Repository\\CommunicationRepository',
        ]);
    }
}
