<?php

namespace ContainerGPhgrvV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommunication2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.DyTFj._.App\Entity\Communication' shared service.
     *
     * @return \App\Entity\Communication
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.DyTFj._": it needs an instance of "App\\Entity\\Communication" but this type has been excluded in "config/services.yaml".');
    }
}
