<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD0Rr18u\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD0Rr18u/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerD0Rr18u.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerD0Rr18u\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerD0Rr18u\App_KernelProdContainer([
    'container.build_hash' => 'D0Rr18u',
    'container.build_id' => '9918c704',
    'container.build_time' => 1770422375,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD0Rr18u');
