<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Publication extends \App\Entity\Publication implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'categorie' => [parent::class, 'categorie', null, 16],
        "\0".parent::class."\0".'communications' => [parent::class, 'communications', null, 16],
        "\0".parent::class."\0".'dateCreation' => [parent::class, 'dateCreation', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'nombreLikes' => [parent::class, 'nombreLikes', null, 16],
        "\0".parent::class."\0".'nombreVues' => [parent::class, 'nombreVues', null, 16],
        "\0".parent::class."\0".'titre' => [parent::class, 'titre', null, 16],
        'categorie' => [parent::class, 'categorie', null, 16],
        'communications' => [parent::class, 'communications', null, 16],
        'dateCreation' => [parent::class, 'dateCreation', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'nombreLikes' => [parent::class, 'nombreLikes', null, 16],
        'nombreVues' => [parent::class, 'nombreVues', null, 16],
        'titre' => [parent::class, 'titre', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
