<?php

namespace ContainerD0Rr18u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WS2NMTService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator._WS2NMT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._WS2NMT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\CommunicationRepository', 'getCommunicationRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\CommunicationRepository',
        ]);
    }
}
