<?php

namespace ContainerD0Rr18u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T2_BUGiService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.t2.BUGi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'publicationRepo' => ['privates', 'App\\Repository\\PublicationRepository', 'getPublicationRepositoryService', true],
            'repo' => ['privates', 'App\\Repository\\CommunicationRepository', 'getCommunicationRepositoryService', true],
        ], [
            'em' => '?',
            'publicationRepo' => 'App\\Repository\\PublicationRepository',
            'repo' => 'App\\Repository\\CommunicationRepository',
        ]);

        if (isset($container->privates['.service_locator.t2.BUGi'])) {
            return $container->privates['.service_locator.t2.BUGi'];
        }

        return $container->privates['.service_locator.t2.BUGi'] = $instance;
    }
}
