<?php

namespace ContainerD0Rr18u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\BackPublicationController::delete' => ['privates', '.service_locator.cZbSAvB', 'get_ServiceLocator_CZbSAvBService', true],
            'App\\Controller\\BackPublicationController::edit' => ['privates', '.service_locator.cZbSAvB', 'get_ServiceLocator_CZbSAvBService', true],
            'App\\Controller\\BackPublicationController::exportPdf' => ['privates', '.service_locator.XoAQrZN', 'get_ServiceLocator_XoAQrZNService', true],
            'App\\Controller\\BackPublicationController::index' => ['privates', '.service_locator.XoAQrZN', 'get_ServiceLocator_XoAQrZNService', true],
            'App\\Controller\\BackPublicationController::new' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\BackPublicationController::show' => ['privates', '.service_locator.BS3Flt3', 'get_ServiceLocator_BS3Flt3Service', true],
            'App\\Controller\\BackPublicationController::statistics' => ['privates', '.service_locator.XoAQrZN', 'get_ServiceLocator_XoAQrZNService', true],
            'App\\Controller\\CommunicationController::delete' => ['privates', '.service_locator.nSjV3Y2', 'get_ServiceLocator_NSjV3Y2Service', true],
            'App\\Controller\\CommunicationController::edit' => ['privates', '.service_locator.t2.BUGi', 'get_ServiceLocator_T2_BUGiService', true],
            'App\\Controller\\CommunicationController::exportPdf' => ['privates', '.service_locator._WS2NMT', 'get_ServiceLocator_WS2NMTService', true],
            'App\\Controller\\CommunicationController::index' => ['privates', '.service_locator.dGSEfNf', 'get_ServiceLocator_DGSEfNfService', true],
            'App\\Controller\\CommunicationController::new' => ['privates', '.service_locator.z0uo5zS', 'get_ServiceLocator_Z0uo5zSService', true],
            'App\\Controller\\CommunicationController::searchAdvanced' => ['privates', '.service_locator._WS2NMT', 'get_ServiceLocator_WS2NMTService', true],
            'App\\Controller\\CommunicationController::show' => ['privates', '.service_locator._WS2NMT', 'get_ServiceLocator_WS2NMTService', true],
            'App\\Controller\\CommunicationController::statistics' => ['privates', '.service_locator._WS2NMT', 'get_ServiceLocator_WS2NMTService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\BackPublicationController:delete' => ['privates', '.service_locator.cZbSAvB', 'get_ServiceLocator_CZbSAvBService', true],
            'App\\Controller\\BackPublicationController:edit' => ['privates', '.service_locator.cZbSAvB', 'get_ServiceLocator_CZbSAvBService', true],
            'App\\Controller\\BackPublicationController:exportPdf' => ['privates', '.service_locator.XoAQrZN', 'get_ServiceLocator_XoAQrZNService', true],
            'App\\Controller\\BackPublicationController:index' => ['privates', '.service_locator.XoAQrZN', 'get_ServiceLocator_XoAQrZNService', true],
            'App\\Controller\\BackPublicationController:new' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\BackPublicationController:show' => ['privates', '.service_locator.BS3Flt3', 'get_ServiceLocator_BS3Flt3Service', true],
            'App\\Controller\\BackPublicationController:statistics' => ['privates', '.service_locator.XoAQrZN', 'get_ServiceLocator_XoAQrZNService', true],
            'App\\Controller\\CommunicationController:delete' => ['privates', '.service_locator.nSjV3Y2', 'get_ServiceLocator_NSjV3Y2Service', true],
            'App\\Controller\\CommunicationController:edit' => ['privates', '.service_locator.t2.BUGi', 'get_ServiceLocator_T2_BUGiService', true],
            'App\\Controller\\CommunicationController:exportPdf' => ['privates', '.service_locator._WS2NMT', 'get_ServiceLocator_WS2NMTService', true],
            'App\\Controller\\CommunicationController:index' => ['privates', '.service_locator.dGSEfNf', 'get_ServiceLocator_DGSEfNfService', true],
            'App\\Controller\\CommunicationController:new' => ['privates', '.service_locator.z0uo5zS', 'get_ServiceLocator_Z0uo5zSService', true],
            'App\\Controller\\CommunicationController:searchAdvanced' => ['privates', '.service_locator._WS2NMT', 'get_ServiceLocator_WS2NMTService', true],
            'App\\Controller\\CommunicationController:show' => ['privates', '.service_locator._WS2NMT', 'get_ServiceLocator_WS2NMTService', true],
            'App\\Controller\\CommunicationController:statistics' => ['privates', '.service_locator._WS2NMT', 'get_ServiceLocator_WS2NMTService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\BackPublicationController::delete' => '?',
            'App\\Controller\\BackPublicationController::edit' => '?',
            'App\\Controller\\BackPublicationController::exportPdf' => '?',
            'App\\Controller\\BackPublicationController::index' => '?',
            'App\\Controller\\BackPublicationController::new' => '?',
            'App\\Controller\\BackPublicationController::show' => '?',
            'App\\Controller\\BackPublicationController::statistics' => '?',
            'App\\Controller\\CommunicationController::delete' => '?',
            'App\\Controller\\CommunicationController::edit' => '?',
            'App\\Controller\\CommunicationController::exportPdf' => '?',
            'App\\Controller\\CommunicationController::index' => '?',
            'App\\Controller\\CommunicationController::new' => '?',
            'App\\Controller\\CommunicationController::searchAdvanced' => '?',
            'App\\Controller\\CommunicationController::show' => '?',
            'App\\Controller\\CommunicationController::statistics' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\BackPublicationController:delete' => '?',
            'App\\Controller\\BackPublicationController:edit' => '?',
            'App\\Controller\\BackPublicationController:exportPdf' => '?',
            'App\\Controller\\BackPublicationController:index' => '?',
            'App\\Controller\\BackPublicationController:new' => '?',
            'App\\Controller\\BackPublicationController:show' => '?',
            'App\\Controller\\BackPublicationController:statistics' => '?',
            'App\\Controller\\CommunicationController:delete' => '?',
            'App\\Controller\\CommunicationController:edit' => '?',
            'App\\Controller\\CommunicationController:exportPdf' => '?',
            'App\\Controller\\CommunicationController:index' => '?',
            'App\\Controller\\CommunicationController:new' => '?',
            'App\\Controller\\CommunicationController:searchAdvanced' => '?',
            'App\\Controller\\CommunicationController:show' => '?',
            'App\\Controller\\CommunicationController:statistics' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]));

        if (isset($container->privates['argument_resolver.service'])) {
            return $container->privates['argument_resolver.service'];
        }

        return $container->privates['argument_resolver.service'] = $instance;
    }
}
