<?php

namespace ContainerD0Rr18u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBackControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\BackController' shared autowired service.
     *
     * @return \App\Controller\BackController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\BackController'] = $instance = new \App\Controller\BackController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\BackController', $container));

        return $instance;
    }
}
