<?php

namespace ContainerD0Rr18u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommunicationControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\CommunicationController' shared autowired service.
     *
     * @return \App\Controller\CommunicationController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\CommunicationController'] = $instance = new \App\Controller\CommunicationController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\CommunicationController', $container));

        return $instance;
    }
}
