<?php

namespace ContainerD0Rr18u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommunicationTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\CommunicationType' shared autowired service.
     *
     * @return \App\Form\CommunicationType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\CommunicationType'] = new \App\Form\CommunicationType();
    }
}
