<?php

namespace ContainerD0Rr18u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommunicationRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\CommunicationRepository' shared autowired service.
     *
     * @return \App\Repository\CommunicationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\CommunicationRepository'] = new \App\Repository\CommunicationRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
