<?php

namespace ContainerD0Rr18u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPublicationRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\PublicationRepository' shared autowired service.
     *
     * @return \App\Repository\PublicationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\PublicationRepository'] = new \App\Repository\PublicationRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
