<?php

namespace ContainerD0Rr18u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPublication2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.cZbSAvB.App\Entity\Publication' shared service.
     *
     * @return \App\Entity\Publication
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.cZbSAvB": it needs an instance of "App\\Entity\\Publication" but this type has been excluded in "config/services.yaml".');
    }
}
