<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGPhgrvV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGPhgrvV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGPhgrvV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGPhgrvV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGPhgrvV\App_KernelDevDebugContainer([
    'container.build_hash' => 'GPhgrvV',
    'container.build_id' => '3d61b997',
    'container.build_time' => 1770581576,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGPhgrvV');
